### ISSUE TITLE
cursor pointer not work

### ISSUE THREAD

**Issue by Liripo** [pyloid/pyloid#11]
Hello Developer:
Thank you very much for developing this useful package.

I don't know if I should ask this question here, the cursor doesn't seem to work.

The simplest example, I used the HTML template you provided and added the following code to index.html .
```html
<div style="cursor: pointer; height: 100px; width: 100px;z-index: 999">pointer</div>
```

**Comment by aesthetics-of-record** [comment]
Thanks!

Fix it.

You can use that feature starting from version 0.17.3
