### ISSUE TITLE
[feature request] Open local files and write

### ISSUE THREAD

**Issue by Liripo** [pyloid/pyloid#4]

**Comment by aesthetics-of-record** [comment]
Yes!

We’ve added a guide on how to leverage PySide6 to implement various features and integrate them directly into Pyloid. This guide demonstrates how users can create their own functionality, like calling PySide6 dialogs, and easily apply them to Pyloid projects.

Moving forward, we plan to wrap various features into Pyloid itself, raising the level of abstraction and simplifying usage significantly. However, for advanced features or those requiring more functionality, users will have the flexibility to implement and integrate them directly through PySide6.

While Pyloid will make core functionalities easily accessible, we will continue to add guides on how users can create more powerful features themselves using PySide6.

---

We have also integrated the file-dialog functionality directly into Pyloid, allowing it to be executed through a method in the framework.

Thank you for your interest, and we are continuously working on updates to improve Pyloid.
