### ISSUE TITLE
QWebChannel is not defined

### ISSUE THREAD

**Issue by guizhenwei** [pyloid/pyloid#6]
Using the following code with URL changed, it reports `QWebChannel is not defined.` whenever i clicked something.

```
from pyloid import Pyloid

app = Pyloid(app_name="Pyloid-App", single_instance=True)

win = app.create_window("pyloid-example")
win.load_url("https://www.example.com")
win.show_and_focus()

app.run()
```

**Comment by aesthetics-of-record** [comment]
`QWebchannel` is used to define js_api in Python. So it does not work on other website URLs.

It only works with html urls or files containing `<script src="qrc:///qtwebchannel/qwebchannel.js"></script>`

if you don't use the js_api, you can ignore that message.
