### ISSUE TITLE
How to efficiently transfer numpy array

### ISSUE THREAD

**Issue by Liripo** [pyloid/pyloid#9]
![image](https://github.com/user-attachments/assets/987db4c2-1004-4c01-817e-b08783e4bb5f)
I have a relatively large image data, saved as numpy array, how can I transfer it to the js side for easy drawing?

**Comment by aesthetics-of-record** [comment]
How about encoding it in base64 and sending it to js in string format?

If you have any additional questions, please let me know.

**Comment by Liripo** [comment]
I tried opencv, it's pretty fast. When the data is large, you can use it like this：
```python
def array_to_base64_png_fast(arr):
    import cv2
    import base64
    img_array = (np.clip(arr, 0, 1) * 255).astype(np.uint8)
  
    success, buffer = cv2.imencode('.png', img_array)
    if success:
        data = base64.b64encode(buffer).decode('utf-8')
        return f'data:image/png;base64,{data}'
    else:
        raise Exception("Failed to encode image")

class api(PyloidAPI):
    @Bridge(result=str)
    def get_image(self):

        img_arr = np.array([[[1,1,1],[0,0,0]]])
        img_uri = array_to_base64_png_fast(img_arr)
        return img_uri
```
